export const coins = [
    "bitcoin",
    "ethereum",
    "tether",
    "bnb",
    "solana",
    "xrp",
    "usd coin",
    "cardano",
    "dogecoin",
    "avalanche",
    "toncoin",
    "polkadot",
    "chainlink",
    "wrapped bitcoin",
    "tron",
    "polygon",
    "bitcoin cash",
    "uniswap",
    "near protocol",
    "litecoin",
    "aptos",
    "internet computer",
    "dai",
    "stacks",
    "filecoin",
    "arbitrum",
    "cosmos",
    "ethereum classic",
    "render token",
    "immutable x",
    "stellar",
    "hedera",
    "the graph",
    "okb",
    "injective",
    "kaspa",
    "veChain",
    "optimism",
    "cronos",
    "pepe",
    "first digital usd",
    "fantom",
    "aion",
    "ripple",
    "eos",
    "ethereum-classic",
    "dash",
    "binance-coin",
    "tezos",
    "zcash",
    "omisego",
    "qtum",
    "0x",
    "bitcoin-gold",
    "bytecoin-bcn",
    "bitshares",
    "lisk",
    "decred",
    "zilliqa",
    "aeternity",
    "maker",
    "digibyte",
    "icon",
    "ontology",
];
